name: dl-mcs
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- python=3.12
- pip
- pytorch=2.4.0
- pytorch-cuda=12.4
- torchvision=0.19.0
- torchaudio=2.4.0
- pip:
  - -r requirements.txt -f https://data.pyg.org/whl/torch-2.4.0+cu124.html
